name: todo_app
description: A simple Flutter to-do app with Firebase
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core
  firebase_core: ^2.25.4

  # Firebase authentication
  firebase_auth: ^4.17.5

  # Cloud Firestore
  cloud_firestore: ^4.15.3

  # Additional common packages
  provider: ^6.1.2
  flutter_hooks: ^0.20.5

  # Optional (if using forms or validation)
  flutter_form_builder: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true