// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEWUtDiqqjzRYUbWAJfnB3JPUZNnhiEws',
    appId: '1:252736223486:web:7633ed2c72bdbd886c8daf',
    messagingSenderId: '252736223486',
    projectId: 'mrl-todo-app',
    authDomain: 'mrl-todo-app.firebaseapp.com',
    storageBucket: 'mrl-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqqiXE9wWmNIImBrxwUO8HVmoU8mBbf4o',
    appId: '1:252736223486:android:753155b8bdd19e816c8daf',
    messagingSenderId: '252736223486',
    projectId: 'mrl-todo-app',
    storageBucket: 'mrl-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbKeMvbTIBH2h615iHk_0ad1XHrRVWD1M',
    appId: '1:252736223486:ios:9ca449b243252b086c8daf',
    messagingSenderId: '252736223486',
    projectId: 'mrl-todo-app',
    storageBucket: 'mrl-todo-app.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbKeMvbTIBH2h615iHk_0ad1XHrRVWD1M',
    appId: '1:252736223486:ios:9ca449b243252b086c8daf',
    messagingSenderId: '252736223486',
    projectId: 'mrl-todo-app',
    storageBucket: 'mrl-todo-app.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEWUtDiqqjzRYUbWAJfnB3JPUZNnhiEws',
    appId: '1:252736223486:web:bd786eddc8a3aa236c8daf',
    messagingSenderId: '252736223486',
    projectId: 'mrl-todo-app',
    authDomain: 'mrl-todo-app.firebaseapp.com',
    storageBucket: 'mrl-todo-app.firebasestorage.app',
  );
}
